### AUTHOR: AHz
### LAST EDIT: 2022-05-07
### WRITTEN IN: R version 4.0.5
### Purpose: AirThings Explorer dashboard


dashboardPage(

    # Application title
    dashboardHeader(title = "Airthings Explorer"),
    
    
    
    # Sidebar with a slider input for number of bins
    dashboardSidebar(
        pickerInput("date_select", "Select Time Range to Show", 
                    choices = c("Date Range" = "dates", 
                                "12 hours" = "12hr", 
                                "24 hours" = "24hr",
                                "36 hours" = "36hr",
                                "48 hours" = "48hr", 
                                "1 week" = "1wk", 
                                "1 month" = "1mo"
                                ),
                    selected = "1wk", 
                    options = list(`actions-box` = TRUE,
                                   title = "Select"),
                    multiple = FALSE),
        conditionalPanel(condition = "input.date_select ==`dates`", 
                         dateRangeInput("date_range", "Date Range:", 
                                        start = min(air_dat_long$date),
                                        end = max(air_dat_long$date),
                                        min = min(air_dat_long$date),
                                        max = max(air_dat_long$date))),
        sidebarMenu(menuItem("Dashboard", tabName = "dashboard", icon = icon("thumb-tack"))),
        sidebarMenu(menuItem("Metrics", tabname = "metrics", icon = icon("area-chart"), startExpanded = TRUE,
                             menuSubItem("Temperature",
                                         tabName = "temp"),
                             menuSubItem("Humidity",
                                         tabName = "humidity"),
                             menuSubItem("Pressure",
                                         tabName = "pressure"),
                             menuSubItem("Radon",
                                         tabName = "radon"),
                             menuSubItem("CO2",
                                         tabName = "co2"),
                             menuSubItem("VOC",
                                         tabName = "voc"),
                             menuSubItem("PM",
                                         tabName = "pm"))),
        sidebarMenu(menuItem("Cooking events + IAQ",
                             tabName = "cooking",
                             icon = icon("cutlery"))),
        sidebarMenu(menuItem("Source code", 
                             icon = icon("github"), 
                             href = "https://github.com/amandabhernandez/airthings_explorer"))
        
    ),
    
    # Show a plot of the generated distribution
    dashboardBody(
        tabItems(
            tabItem(tabName = "dashboard",
                    tags$head(includeHTML(("google-analytics.html"))),
                    fluidRow(h3(" Median of Measurements"),
                             p("Median of all measurements in the currently selected time range"),
                             infoBoxOutput("temp_current"),
                             infoBoxOutput("humidity_current"),
                             infoBoxOutput("pressure_current"),
                             infoBoxOutput("radon_current"),
                             infoBoxOutput("co2_current"),
                             infoBoxOutput("voc_current"),
                             infoBoxOutput("pm2.5_current"),
                             infoBoxOutput("pm10_current")
                             ),
                    fluidRow(h3(" Time Series Graphs"), 
                             uiOutput("metric"),
                             #uiOutput("roavg"),
                             plotlyOutput("airplot"))
            ),
            tabItem(tabName = "temp",
                    fluidRow(box(title = "Time Series Graph",
                                 plotlyOutput("tempplot"), width = 12, status = "primary", 
                                 solidHeader = TRUE),
                             box(width = 6, status = "info", 
                                 solidHeader = TRUE, 
                                 title = "Distribution of temperature measurements", 
                                 plotlyOutput("temp_density")),
                             box(width = 6, status = "info",
                                 solidHeader = TRUE,
                                 title = "Comparison",
                                 pickerInput("temp_y_comp", 
                                             choices = c(unique(air_dat_long$metric)),
                                             options = list(`actions-box` = TRUE,
                                                            title = "Select"),
                                             multiple = FALSE),
                                 plotlyOutput("temp_xy")))),
            tabItem(tabName = "humidity",
                    fluidRow(box(title = "Time Series Graph",
                                 plotlyOutput("humplot"), width = 12, status = "primary", 
                                 solidHeader = TRUE),
                             box(width = 6, status = "info", 
                                 solidHeader = TRUE, 
                                 title = "Distribution of humidity measurements", 
                                 plotlyOutput("hum_density")),
                             box(width = 6, status = "info",
                                 solidHeader = TRUE,
                                 title = "Comparison",
                                 pickerInput("hum_y_comp", 
                                             choices = c(unique(air_dat_long$metric)),
                                             options = list(`actions-box` = TRUE,
                                                            title = "Select"),
                                             multiple = FALSE),
                                 plotlyOutput("hum_xy")))),
            tabItem(tabName = "pressure",
                    fluidRow(box(title = "Time Series Graph",
                                 plotlyOutput("pressplot"), width = 12, status = "primary", 
                                 solidHeader = TRUE),
                             box(width = 6, status = "info", 
                                 solidHeader = TRUE, 
                                 title = "Distribution of pressure measurements", 
                                 plotlyOutput("pressure_density")),
                             box(width = 6, status = "info",
                                 solidHeader = TRUE,
                                 title = "Comparison",
                                 pickerInput("press_y_comp", 
                                             choices = c(unique(air_dat_long$metric)),
                                             options = list(`actions-box` = TRUE,
                                                            title = "Select"),
                                             multiple = FALSE),
                                 plotlyOutput("press_xy")))),
            tabItem(tabName = "radon",
                    fluidRow(plotlyOutput("radplot"),
                             plotlyOutput("rad_density"))),
            tabItem(tabName = "co2",
                    fluidRow(box(title = "Time Series Graph",
                                 plotlyOutput("co2plot"), width = 12, status = "primary", 
                                 solidHeader = TRUE),
                             box(width = 6, status = "info", 
                                 solidHeader = TRUE, 
                                 title = "Distribution of CO2 measurements", 
                                 plotlyOutput("co2_density")),
                             box(width = 6, status = "info",
                                 solidHeader = TRUE,
                                 title = "Comparison",
                                 pickerInput("co2_y_comp", 
                                             choices = c(unique(air_dat_long$metric)),
                                             options = list(`actions-box` = TRUE,
                                                            title = "Select"),
                                             multiple = FALSE),
                                 plotlyOutput("co2_xy")))),
            tabItem(tabName = "voc",
                    fluidRow(box(title = "Time Series Graph",
                                 plotlyOutput("vocplot"), width = 12, status = "primary", 
                                 solidHeader = TRUE),
                             box(width = 6, status = "info", 
                                 solidHeader = TRUE, 
                                 title = "Distribution of VOC measurements", 
                                 plotlyOutput("voc_density")),
                             box(width = 6, status = "info",
                                 solidHeader = TRUE,
                                 title = "Comparison",
                                 pickerInput("voc_y_comp", 
                                             choices = c(unique(air_dat_long$metric)),
                                             options = list(`actions-box` = TRUE,
                                                            title = "Select"),
                                             multiple = FALSE),
                                 plotlyOutput("voc_xy")))),
            tabItem(tabName = "pm",
                    fluidRow(box(title = "Time Series Graph",
                                 plotlyOutput("pmplot"), width = 12, status = "primary", 
                                 solidHeader = TRUE),
                             box(width = 6, status = "info", 
                                 solidHeader = TRUE, 
                                 title = "Distribution of PM measurements", 
                                 plotlyOutput("pm_density")),
                             box(width = 6, status = "info",
                                 solidHeader = TRUE,
                                 title = "Comparison",
                                 pickerInput("pm_y_comp", 
                                             choices = c(unique(air_dat_long$metric)),
                                             options = list(`actions-box` = TRUE,
                                                            title = "Select"),
                                             multiple = FALSE),
                                 plotlyOutput("pm_xy")))),
            tabItem(tabName = "cooking",
                    fluidRow(box(title = "Cooking events", width = 12, 
                                 status = "primary", solidHeader = TRUE,
                                 DT::dataTableOutput("cooking_log")),
                             # box(title = "Cooking events time series", width = 12, 
                             #     status = "primary", solidHeader = TRUE,
                             #     plotlyOutput("cooking_events_TS")),
                             box(title = "Avg change over capture window", width = 12, 
                                 status = "primary", solidHeader = TRUE,
                                 plotlyOutput("avg_change"))))
            )
        
    )
    
)

